### PR TITLE
Various crash fixes

### PR DESCRIPTION
**Pull request by ScribbleTAS**
- [1.16.1+] Fixed mod being compiled in the wrong java version
- [1.20.1] Fixed IngameHud crashing

### CODE REVIEW

**Review by PancakeTAS — CHANGES_REQUESTED** [review]
NO NO NO! Don't remove the compatibility lines or change them to 16/17!
Instead, put them back and set the version to 1.8. That way compilation will always work and eclipse won't accidentally suggest java 9+ features to you.

**Comment by ScribbleTAS** [comment]
@PancakeTAS So, the compatibility for 1.14-1.16.5 is set in the common.gradle and it is on 1.8. For the others, this is actually a revert for an earlier commit, where I botched everything (74dd9d58eade35fbb326f47cbe9f4cad35350286). Back then I somehow threw everything away https://github.com/MinecraftTAS/LoTAS/commit/74dd9d58eade35fbb326f47cbe9f4cad35350286#diff-d2ece9f768eaf134f0487a05b32c9a3b1ecce75d4b7a7beb82abd9466c7e6631L5-R9 . It should now be correct as it was before.

And starting with 1.18, Mojang uses Java 17 features...

**Comment by PancakeTAS** [comment]
I see. Still you shouldn't set the java compatibility level above 8, ever.

**Comment by ScribbleTAS** [comment]
> I see. Still you shouldn't set the java compatibility level above 8, ever.

I don't care anymore

**Review by PancakeTAS — APPROVED** [review]
your funeral

**Pull request merged**
